### ISSUE TITLE
Can I get neighbor cells of one particular cell in js?

### ISSUE THREAD

**Issue by greentec** [jimmyland/voro#40]
Hello, firstly, thanks for great repository. 
I'm using this for manipulating voronoi grid in 3d space.
But I want get neighbor cells of one particular cell, and I couldn't find the way. 
Is this possible with current source code, or need additional update? Thanks.

**Comment by jimmyland** [comment]
Thanks!

The cell neighbors are computed in the cpp code but only exposed to js via `cell_neighbor_from_vertex` which is probably not what you want.

To expose all the neighbors in js easily you'd need to add a function to vorowrap.cpp and recompile the cpp code.  Function would probably look something kinda like this:
```
    vector<int> cell_neighbors(int cell) {
        gl_computed.ensure_computed(*this, cell);
        CellCache *cache = gl_computed.get_cache(cell);
        if (!cache) return vector<int>();
        return cache->neighbors;
    }
```

**Comment by greentec** [comment]
Thank you for your fast feedback. I will try recompile cpp and tell you how's it going.

**Comment by greentec** [comment]
I succeeded complie with this script. 
``` bash
emcc vorowrap.cpp voro++/voro++.cc --bind -s ALLOW_MEMORY_GROWTH=1 -s NO_EXIT_RUNTIME=1 -s ASSERTIONS=1 -s DEMANGLE_SUPPORT=1 -std=c++11 -O2 --llvm-opts 2 -o vorowrap.js
```

But sorry for bothering you, I have another question. 
When I hit function `cell_neighbors`, I got this value.
``` Javascript
v3.voro.cell_neighbors(0)
> VectorInt {$$: {…}}
> $$:
> count: {value: 1}
> ptr: 5524808
> ptrType: RegisteredPointer {name: "VectorInt*", registeredClass: RegisteredClass, isReference: false, isConst: false, isSmartPointer: false, …}
> __proto__: Object
> __proto__: ClassHandle
```

The cell 0 is a visible cell in below image, so I thought its neighbors are almost all other cells - 1, 2, 3, etc. But I got just one ptr value. 
![q1](https://user-images.githubusercontent.com/6878615/53248760-d7fdc580-36f9-11e9-9628-13357282dc6d.png)

So my question is, how can I get other neighbor cell indexes in js? (like `{0:[1,2,3], 1:[0,2,3,4]}`) 
I'm sorry I took your time.

**Comment by jimmyland** [comment]
try `v3.voro.cell_neighbors(0).size()` to get the size and `v3.voro.cell_neighbors(0).get(0)` to get the first neighbor, etc

note you will get some negative cell numbers for cells that neighbor the bounds of the space (these indicate which wall you are neighboring)

**Comment by jimmyland** [comment]
for context, VectorInt is a class wrapping up a c++ std::vector; there is a little documentation on it and a usage example here: https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#built-in-type-conversions

**Comment by greentec** [comment]
Wow, this works! Your advice has been a great help to me.
``` Javascript
v3.voro.cell_neighbors(0).size()
> 10
for (let i = 0; i < v3.voro.cell_neighbors(0).size(); i += 1) {
	console.log(v3.voro.cell_neighbors(0).get(i))
}
> 9
> -2
> 2
> 6
> 4
> 3
> 1
> 7
> 8
> 5
```
